image: node:latest

stages:
  - deployTest
  - deploy

cache:
  paths:
  - node_modules/

deployFamilyTest:
  only:
    - test
  stage: deployTest
  script:
    - npm i
    - cat $TEST_FAMILY_CLIENT > .env.production
    - npm run build
    - rsync -azvhq build/ /home/${DEPLOY_USER}/services/test-family-fe/build --delete
    - bash /home/${DEPLOY_USER}/scripts/test-family-fe.sh

deployFamily:
  only:
    - master
  stage: deploy
  script:
    - npm i
    - cat $FAMILY_CLIENT > .env.production
    - npm run build
    - rsync -azvhq build/ /home/${DEPLOY_USER}/services/family-fe/build --delete
    - bash /home/${DEPLOY_USER}/scripts/family-fe.sh
