image: node:latest

stages:
  - deployTest
  - deploy

cache:
  paths:
  - node_modules/

deployFamilyTest:
  only:
    - test
  stage: deployTest
  before_script: 
    - apt-get update -y
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - which rsync || ( apt-get update -y && apt-get install rsync -y )
    - mkdir -p ~/.ssh
    - echo -e "$SSH_SECRET_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - npm i
    - echo $GRAPHQL_END_POINT
    - GRAPHQL_END_POINT=graphqlhrm CLOUDINARY_NAME=$CLOUDINARY_NAME CLOUDINARY_UPLOAD_PRESET=$TEST_CLOUDINARY_UPLOAD_PRESET FIREBASE_API_KEY=$TEST_FIREBASE_API_KEY FIREBASE_AUTH_DOMAIN=$TEST_FIREBASE_AUTH_DOMAIN FIREBASE_DATABASE_URL=$TEST_FIREBASE_DATABASE_URL FIREBASE_PROJECT_ID=$TEST_FIREBASE_PROJECT_ID FIREBASE_STORAGE_BUCKET=$TEST_FIREBASE_STORAGE_BUCKET FIREBASE_MESSAGING_SENDER_ID=$TEST_FIREBASE_MESSAGING_SENDER_ID FIREBASE_APP_ID=$TEST_FIREBASE_APP_ID FIREBASE_MEASUREMENT_ID=$TEST_FIREBASE_MEASUREMENT_ID npm run build
    - rsync -aO -e "ssh -p 22 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" build/ ${DEPLOY_USER}@${DEPLOY_SERVER}:/home/${DEPLOY_USER}/services/test-family-fe/build --delete
    - ssh -o "StrictHostKeyChecking=no" ${DEPLOY_USER}@${DEPLOY_SERVER} 'bash scripts/test-family-fe.sh'

deployFamily:
  only:
    - master
  stage: deploy
  before_script: 
    - apt-get update -y
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - which rsync || ( apt-get update -y && apt-get install rsync -y )
    - mkdir -p ~/.ssh
    - echo -e "$SSH_SECRET_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - npm i
    - CLOUDINARY_NAME="$CLOUDINARY_NAME" CLOUDINARY_UPLOAD_PRESET="$CLOUDINARY_UPLOAD_PRESET" GRAPHQL_END_POINT="$GRAPHQL_END_POINT" FIREBASE_API_KEY="$FIREBASE_API_KEY" FIREBASE_AUTH_DOMAIN="$FIREBASE_AUTH_DOMAIN" FIREBASE_DATABASE_URL="$FIREBASE_DATABASE_URL" FIREBASE_PROJECT_ID="$FIREBASE_PROJECT_ID" FIREBASE_STORAGE_BUCKET="$FIREBASE_STORAGE_BUCKET" FIREBASE_MESSAGING_SENDER_ID="$FIREBASE_MESSAGING_SENDER_ID" FIREBASE_APP_ID="$FIREBASE_APP_ID" FIREBASE_MEASUREMENT_ID="$FIREBASE_MEASUREMENT_ID" npm run build
    - rsync -aO -e "ssh -p 22 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" build/ ${DEPLOY_USER}@${DEPLOY_SERVER}:/home/${DEPLOY_USER}/services/family-fe/build --delete
    - ssh -o "StrictHostKeyChecking=no" ${DEPLOY_USER}@${DEPLOY_SERVER} 'bash scripts/family-fe.sh'
